### ISSUE TITLE
Fix python (SyntaxError: invalid syntax. Perhaps you forgot a comma?)

### ISSUE THREAD

**Issue by YorhaX2P** [drchannn/drchannn-codevein-pak-pc-to-ps4#1]
Find 110 and 112 line

**Before 110:**

`umodel_export_cmd=[umodel_exe,"-game="+GAMETAG","-path="+TMP_PATH+"\\pak","-notgacomp","-export","*"]`
	
**After 110:**
`umodel_export_cmd=[umodel_exe, "-game=" + GAMETAG, "-path=" + TMP_PATH + "\\pak", "-notgacomp", "-export", "*"]`

**Before 112:**

`umodel_export_cmd=[umodel_exe,"-game="+GAMETAG","-path="+TMP_PATH+"\\pak","-dds","-export","*"]`

**After 112:**
`umodel_export_cmd=[umodel_exe, "-game=" + GAMETAG, "-path=" + TMP_PATH + "\\pak", "-dds", "-export", "*"]`

**Comment by drchannn** [comment]
Fixed now, thx
