### ISSUE TITLE
pak file not genarated 

### ISSUE THREAD

**Issue by Otakugamer1412** [drchannn/drchannn-codevein-pak-pc-to-ps4#3]
i have test the tool but bit dosnet work , the tool not generated new pak file

**Comment by drchannn** [comment]
What message that u see on program, what mod are u try to convert??

**Comment by Otakugamer1412** [comment]
> What message that u see on program, what mod are u try to convert??

No error message , its show message the new pak is created but there is no new pak file in directory !

**Comment by Otakugamer1412** [comment]
.

**Comment by drchannn** [comment]
Can you send a video, and mod you are try to converting please

**Comment by Otakugamer1412** [comment]
> Can you send a video, and mod you are try to converting please

i test kena , soulcalibur mods 
![image](https://github.com/user-attachments/assets/9816b158-afef-4597-8155-20463a1fdea1)

as shown in the above its show oak is created ! but there is no actually new pak file created inside folder

**Comment by Otakugamer1412** [comment]
.

**Comment by drchannn** [comment]
https://github.com/user-attachments/assets/aba57371-18da-4742-a2ec-25774c73b7b3

I download from release page and tested and dont see any problem

**Comment by Otakugamer1412** [comment]
> test.mp4 
> I download from release page and tested and dont see any problem

will , still not work for me , no new pak file created

**Comment by Otakugamer1412** [comment]
ok i figure out  the issue , with unreal pack file i have put new one and work now , thanks
