### ISSUE TITLE
soulcalibur & kena issue

### ISSUE THREAD

**Issue by Otakugamer1412** [drchannn/drchannn-codevein-pak-pc-to-ps4#4]
Kena Mods have texture problem  , i have convert mode , the body is  gray out texture
soulcalibur have issue with showing deleted mesh

**Comment by drchannn** [comment]
please put mods that have problems

**Comment by Otakugamer1412** [comment]
https://www.nexusmods.com/kenabridgeofspirits/mods/24?tab=files&file_id=54
https://www.nexusmods.com/soulcaliburvi/mods/2?tab=files&file_id=23

**Comment by drchannn** [comment]
Tested,

for kena converstion its ok, but I think that need to redo map file (I dont know how),
for soulcalibur textures are ok, program only convert textures files, sorry
